//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPizza
    {
        public int PizzaId { get; set; }
        public string PizzaSize { get; set; }
        public string PizzaIngredients { get; set; }
        public int TotalAmount { get; set; }
    }
}
